import EmberFlexberryDummyChildLevel1EditController from '../ember-flexberry-dummy-child-level1-edit';

var EmberFlexberryDummyChildLevel1EditNewController = EmberFlexberryDummyChildLevel1EditController;
export default EmberFlexberryDummyChildLevel1EditNewController;
