import EmberFlexberryDummyChildLevel2EditController from '../ember-flexberry-dummy-child-level2-edit';

var EmberFlexberryDummyChildLevel2EditNewController = EmberFlexberryDummyChildLevel2EditController;
export default EmberFlexberryDummyChildLevel2EditNewController;
